### ISSUE TITLE
on/off lose context in IE8

### ISSUE THREAD

**Issue by petrbela** [HubSpot/youmightnotneedjquery#10]
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget.addEventListener

> There is a drawback to attachEvent, the value of this will be a reference to the window object instead of the element on which it was fired.

The correct way to do it is

``` js
function addEventListener(el, eventName, handler) {
  if (el.addEventListener) {
    el.addEventListener(eventName, handler)
  } else {
    el.attachEvent('on' + eventName, function() {
      handler.apply(el, arguments);
    })
  }
}

addEventListener(el, eventName, handler)
```

**Comment by zackbloom** [comment]
This is where this site gets tricky, cause on the one hand, we want to make the point that things are pretty simple most of the time, on the other, we don't want to provide a faulty resource in those edge cases.  The thing to do might be to create a place to explain the differences, or to just link everything to the MDN.

**Comment by tomByrer** [comment]
> create a place to explain the differences

Perhaps a toggle for "More information" to open a hidden paragraph for deeper explanations?
Also useful for [security concerns](https://github.com/HubSpot/youmightnotneedjquery/pull/21#issuecomment-33767238)

> or to just link everything to the MDN

Or both?

**Comment by dustMason** [comment]
I just submitted a pull request (issue #62) before I saw this one. I'd like to argue that this is not an edge case and instead ensures the behavior that all users would expect.
