### ISSUE TITLE
IE9 (& EI10) and below don't have FULL classList support.

### ISSUE THREAD

**Issue by frqnck** [HubSpot/youmightnotneedjquery#107]
You need a classList polyfills/shims as this property is not supported by IE9 and lower.

Following entries are wrongly indicating IE8+ support:
http://youmightnotneedjquery.com/#add_class
http://youmightnotneedjquery.com/#has_class
http://youmightnotneedjquery.com/#remove_class

This one indicates IE9+ support:
http://youmightnotneedjquery.com/#toggle_class

**Comment by zackbloom** [comment]
All the ones you're referring to clearly check for the existence of `classList`, and have appropriate fallbacks: https://www.dropbox.com/s/6pw4tteni1zwslv/Screenshot%202015-01-22%2022.12.31.png?dl=0

**Comment by frqnck** [comment]
These fallbacks will work with HTMLElement but fail with SVGElement, ... 

On IE10 and lower, only an adequate polyfills/shims can properly handle the Element variations.

Maybe you could indicate that you are only targeting HTMLElement.
