### ISSUE TITLE
Ajax post request wrong argument to send

### ISSUE THREAD

**Issue by matthisk** [HubSpot/youmightnotneedjquery#118]
Supplying send with a data object will not work, the data needs to be encoded to a string in the form of 'key=value&...' or atleast do something like JSON.stringify on the data object. Am I missing something? because trying this does not work for me and the Mozilla docs also do not subscribe this behavior for the send method: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#send()

Mentioned code:

``` javascript
var request = new XMLHttpRequest();
request.open('POST', '/my/url', true);
request.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');
request.send(data);
```

**Comment by nobuf** [comment]
I thought it is misleading too. `data` is most likely an object like `{a: 1, b: 2}` (though jQuery allows string type as well), in that case it should be converted to a query string. The below snippet works IE9+:

``` javascript
var request = new XMLHttpRequest();
request.open('POST', '/my/url', true);
request.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');
request.send(Object.keys(data).map(function(k) {
    return encodeURIComponent(k) + '=' + encodeURIComponent(data[k])
}).join('&'));
```

see http://stackoverflow.com/a/14525299/297679

**Comment by Abbondanzo** [comment]
`data` can also be a `FormData`, `Blob`, or `Buffer`, which cannot be stringified. Going to keep this as is
