### ISSUE TITLE
Offset section not working properly in Firefox

### ISSUE THREAD

**Issue by bfintal** [HubSpot/youmightnotneedjquery#122]
Found out that FF was not working properly because `document.body.scrollTop` was returning 0 for that browser only.

Switching it to the more reliable `window.pageYOffset` works.

Same goes with `document.body.scrollLeft` to `window.pageXOffset`.

Original offset code:

```
var rect = el.getBoundingClientRect()

{
  top: rect.top + document.body.scrollTop,
  left: rect.left + document.body.scrollLeft
}
```

Revised offset code:

```
var rect = el.getBoundingClientRect()

{
  top: rect.top + window.pageYOffset,
  left: rect.left + window.pageXOffset
}
```

**Comment by dmitry** [comment]
PS. window.pageYOffset is not supported below IE 9.

**Comment by bfintal** [comment]
@dmitry We should note that in the offset section if it's changed to this: IE10+

**Comment by Krinkle** [comment]
This is a duplicate of https://github.com/HubSpot/youmightnotneedjquery/issues/85.

**Comment by Abbondanzo** [comment]
Closing in favor of #85
