### ISSUE TITLE
still working on this?

### ISSUE THREAD

**Issue by hueitan** [HubSpot/youmightnotneedjquery#124]
Any update from project? Seems no update from Jan.

Awesome project, looks like it can be more. :+1:

**Comment by banderson** [comment]
@huei90 I'll be working on the issues queue in this project, so perhaps some more activity shortly :)

Anything specific you're asking about?

**Comment by hueitan** [comment]
This is very useful project to find utility code!! It's really awesome! Hopefully this can be frequently update so that others can find code easily.

What can we do on helping this?

**Comment by Abbondanzo** [comment]
We're back open for business. I've been slowly sifting through the backlog of issues and tagging them, but feel free to create additional issues/PRs as needed. Thanks :)
