### ISSUE TITLE
ES6 Code examples

### ISSUE THREAD

**Issue by banderson** [HubSpot/youmightnotneedjquery#125]
With the rise of the [transpilers](https://babeljs.io/), it would be useful to list ES6 versions of the code samples to help encourage good, idiomatic patterns. I'll hopefully be working on a PR to bring support similar to what you see on http://gaearon.github.io/react-dnd/

**Comment by mattpilott** [comment]
@banderson ES6 would be really handy. I use the site a lot and really only support IE11+ (edge) and then the last 2-3 versions of all the other browsers. Having an IE11 toggle plus ES6 examples would be magic.

**Comment by hdl-helsinki** [comment]
+1

**Comment by filips123** [comment]
Any update? Now, almost every browser supports ES6 even without transpilers. Even IE11 has some partial support.

I would recommend changing "What's the oldest version of IE you need to support?" field to also include IE11 and "No IE support" where the latter would show ES6 code and former would show ES6 code that is supported in IE11 (not much but still).

**Comment by FranDias** [comment]
Issue is noted and I agree but the generator is broken. Making a Change is on par with a rewrite. A rethink of the project would be nice (and is it actually useful still?)

**Comment by filips123** [comment]
I think that this project might now be even more useful, as ES6+ is supported in almost every browser, and some things can now be done more easily with it.

**Comment by FranDias** [comment]
Fair point. Could even extend to not needing underscore too.


I have a sabbatical coming up. I’ll weigh this abs a project to keep me occupied. Thanks for speaking up
