### ISSUE TITLE
jQuery's `.serialize()` replacement

### ISSUE THREAD

**Issue by gtomitsuka** [HubSpot/youmightnotneedjquery#126]
Hello,

I'm migrating my project and removing jQuery.
I found myself no native alternative to [.serialize()](https://api.jquery.com/serialize/) and youmightnotneedjquery also didn't show a simple solution. I'd recommend adding it to the page.

Thanks!

**Comment by mhriemers** [comment]
http://stackoverflow.com/questions/11661187/form-serialize-javascript-no-framework

**Comment by fabien-michel** [comment]
Why the proposed solution is not present on youmightnotneedjquery ?
