### ISSUE TITLE
A mention of jQuery's support for custom builds.

### ISSUE THREAD

**Issue by jdalton** [HubSpot/youmightnotneedjquery#13]
I think a note on jQuery's support of custom builds for 1.9+ and 2+ would align with the `youmightnotneedjquery` sentiment:

> Maybe you can include a few lines of utility code, and forgo the requirement. If you're only targeting more modern browsers, you might not need anything more than what the browser ships with.

For more info on custom builds check out jQuery's [readme](https://github.com/jquery/jquery/blob/master/README.md#custom-build-examples).

The builds even support [removing Sizzle](https://github.com/jquery/jquery/#modules) and using `querySelectorAll`

> As a special case, you may also replace Sizzle by using a special flag `grunt custom:-sizzle`.
> - **sizzle**: The Sizzle selector engine. When this module is excluded, it is replaced by a rudimentary selector engine based on the browser's `querySelectorAll` method that does not support jQuery selector extensions or enhanced semantics. See the selector-native.js file for details.
> 
> _Note_: Excluding Sizzle will also exclude all jQuery selector extensions (such as `effects/animatedSelector` and `css/hiddenVisibleSelectors`).

**Comment by zackbloom** [comment]
I don't think jQuery getting smaller is really the solution.  I don't personally have a problem with it's size, or its use in websites.  The purpose of this is to expose people to the future of reasonably-designed browsers which don't need a compatibility layer built on top, and to try to convince library developers to not introduce a dependency like this at all.

**Comment by jdalton** [comment]
> The purpose of this is to expose people to the future of reasonably-designed browsers which don't need a compatibility layer built on top, and to try to convince library developers to not introduce a dependency like this at all.

Maybe a shout out to the fact that jQuery 2.0 [is for modern browsers](http://jquery.com/download/#jquery-2-x)?

**Comment by zackbloom** [comment]
But the whole point is that you don't really need it...  If you read this site and decide that the whole `extend` bit is way too much to deal with, I would rather point you towards lo-dash than a monolithic library that does eight different unrelated things.

**Comment by jdalton** [comment]
> But the whole point is that you don't really need it...

A quick browse of jQuery 2 source shows that even modern browsers need love and fixes for some issues. I think that at the very least you all could add a disclaimer stating that the alternatives suggested by `youmightnotneedjquery` work for a narrow set of scenarios/tested-cased and may not necessarily be guaranteed for wider support.

For example you note that `cloneNode(...)` is OK for IE8+ but it's a nest of bugs that affects even modern browsers.
