### ISSUE TITLE
Need implementation of `.toArray()`

### ISSUE THREAD

**Issue by adamschwartz** [HubSpot/youmightnotneedjquery#131]

**Comment by giacomocerquone** [comment]
I provided it. Check the last open PR please, and sorry for the double link!

**Comment by ndugger** [comment]
Wouldn't `Array.from(myNodeListHere)` be the modern equivalent? I use it a good bit on my [You Don't Need jQuery](https://github.com/ndugger/youdontneedjquery) repo, which is supposed to be a more up-to-date version of this repo.
