### ISSUE TITLE
fadeIn example is incorrect in IE10+

### ISSUE THREAD

**Issue by helarqjsc** [HubSpot/youmightnotneedjquery#140]
Take a look:
![screenshot](https://api.monosnap.com/rpc/file/download?id=LnwVOq1ojAepVNRkGJq00cLW17jX7u)
The problem is that `$(el).fadeIn()` sets `display: block` on the element, so it can be completely hidden with `display: none` initially, while the IE10 example only changes `opacity`, meaning that the element has to have `display: block` (or anything else except `none`), so it's not hidden completely. The element has to take space on the page and be opaque. It's not a problem by itself, it's just that these examples are not equivalent and the example on the right cannot completely replace jQuery version.

**Comment by MattyBalaam** [comment]
This is going to change in jQuery 3: http://blog.jquery.com/2015/07/13/jquery-3-0-and-jquery-compat-3-0-alpha-versions-released/

**Comment by helarqjsc** [comment]
Sure, but it's not even released yet and 99.9% of sites use older jQuery version, so if someone tries to replace a jQuery fadeIn function call with the one provided on the site, nothing will work.

**Comment by viniciuskneves** [comment]
@helarqjsc I've read the documentation and @MattyBalaam link about it. So I decided to PR it as jQuery 3 is available only on alpha versions.

**Comment by MattyBalaam** [comment]
But what if the item should be 'table', 'inline' or 'list-item' for example? Maybe I am wrong, but I'm not sure the purpose of the site is a database of 'drop-in' exact replacements for inexperienced developers, rather providing a quick reference of similar solutions as suggested alternatives.

**Comment by viniciuskneves** [comment]
It is exactly the kind of thing they want to fix in jQuery 3. Right now is overrides always to 'block' when you use .show() or .fadeIn() for example. I also don't like it. Just tried to keep it equivalent to jQuery.

**Comment by MattyBalaam** [comment]
This is not the case: http://jsfiddle.net/tgkvcq8p/

**Comment by viniciuskneves** [comment]
@MattyBalaam Indeed. I tried the same with span here and it look to not override the display property. I tested it on Chrome. Do you have access to IE10 to test it? If it works on the same way?

**Comment by MattyBalaam** [comment]
As they say in the article they make a number of guesses and assumptions pre-jQuery about which display property to set it to, and that is one of a number of reasons they are moving away from this route.

I have not found a browser which will not set the inline style in this way with jQuery. Among those they support at least this is expected.

**Comment by viniciuskneves** [comment]
Ok. Thanks for this discussion. I will close the PR as it looks to not make sense anymore :stuck_out_tongue_closed_eyes:

**Comment by anorudes** [comment]
https://jsfiddle.net/tgtuLc98/3/ it doesn't work

**Comment by anorudes** [comment]
https://jsfiddle.net/tgtuLc98/4/ it doesn't work

**Comment by anorudes** [comment]
The example https://jsfiddle.net/tgtuLc98/9/ doesn't work too. There are two ways to do this:
1) https://jsfiddle.net/tgtuLc98/10/
2) https://jsfiddle.net/tgtuLc98/11/

The second method is better

**Comment by viniciuskneves** [comment]
@anorudes We were discussing ways of not changing the 'display' itself. So when defining the class "hide" you shouldn't add display: none, while "show" shouldn't have display: block.

Have you tried this one on IE10? (https://jsfiddle.net/tgtuLc98/3/)

If it works on IE10 so youmightnotneedjquery is right.

**Comment by MattyBalaam** [comment]
Their method works me for me. Tested on Firefox and Chrome:

https://jsfiddle.net/jndn4L3e/1/

**Comment by anorudes** [comment]
"display: none" need for alternative "hide" and "fade". Otherwise, it works differently
