### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by rememberlenny** [HubSpot/youmightnotneedjquery#142]
http://www.isitdownrightnow.com/youmightnotneedjquery.com.html

**Comment by rileyjshaw** [comment]
Confirmed

**Comment by zackbloom** [comment]
The team at Hubspot is working on it, thanks for letting us know.

**Comment by timmfin** [comment]
Yup, we're very sorry about that. Trying to get things back up as we speak...

**Comment by timmfin** [comment]
Ok, the issue has been fixed and after things propagate again, this should be good (works for me).
