### ISSUE TITLE
AJAX alternative add "Fetch API"

### ISSUE THREAD

**Issue by chenghaoc** [HubSpot/youmightnotneedjquery#143]
Fetch API maybe can be considered as one alternative for AJAX.
Browser gradually supports it (http://caniuse.com/#search=fetch). There's also a polyfill (https://github.com/github/fetch) for old browsers.

**Comment by mheiber** [comment]
agree

**Comment by kasperpeulen** [comment]
thisss

**Comment by KaraAJC** [comment]
I'd like to work on this issue! expanding on changes from #171

**Comment by Abbondanzo** [comment]
Closing this out since the polyfill alternative was suggested in #171
