### ISSUE TITLE
fadeOut with callback

### ISSUE THREAD

**Issue by PAEz** [HubSpot/youmightnotneedjquery#146]
Just wondering if anyone had a good way of doing this or any view on the way I do it.
Here's what I came up with...
http://plnkr.co/edit/gP7YbD?p=preview
I needed it to make toast.js work without jq, here's how it ended up...
http://plnkr.co/edit/1aaqGK?p=preview
Any points would be appreciated.

**Comment by zackbloom** [comment]
What's the goal?
