### ISSUE TITLE
Contribution: improved functionality in some functions

### ISSUE THREAD

**Issue by KingSora** [HubSpot/youmightnotneedjquery#149]
Hi.

This is a very nice project and I am really glad someone did this!
Anyway, some alternative functions could have "more" functionality.

For example the "removeClass" function in jquery removes all classes if no parameter is passed. 
So I've updated some function of yours:

**RemoveClass** (removes all classes if no className parameter is given)

``` javascript
function removeClass(el, className) {
    if(className === undefined)
        el.className = '';
    else if (el.classList)
      el.classList.remove(className);
    else
      el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
}
```

**Each** (loops trough object if the passed array is a object and passes key + value to callback func)

``` javascript
function forEach(array, fn) {
    if(typeof array === 'object')
    {
        for (var key in array) {
            if (array.hasOwnProperty(key)) {
                fn(key, array[key]);
            }
        }
    }
    else if (array !== undefined)
    {
        for (var i = 0; i < array.length; i++)
            fn(array[i], i);
    }
}
```

**addEventListener**: (support now multiple eventNames separated with a blank " ")

``` javascript
function addEventListener(el, eventName, handler) {
    forEach(eventName.split(' '), function(i, value) {
        if (el.addEventListener) {
            el.addEventListener(value, handler);
        } else {
            el.attachEvent('on' + value, function(){
                handler.call(el);
            });
        }
    });
}
```

**removeEventListene**r: (support now multiple eventNames separated with a blank " ")

``` javascript
function removeEventListener(el, eventName, handler) {
    forEach(eventName.split(' '), function(i, value) {
        if (el.removeEventListener)
            el.removeEventListener(value, handler);
        else
            el.detachEvent('on' + value, handler);
    });
}
```

Maybe I will find some more functions to improve. I hope my code is valid and I helped you out a little bit :)

Best regards,
Sora

**Comment by ndugger** [comment]
In my opinion, this is overcomplicating what this repo is trying to solve; It's trying to make a point about how you don't need to use a library anymore, because methods now exist in the native APIs. What you're doing here is essentially creating a new library of methods to handle DOM interactions, which is exactly what jQuery does.

**Comment by MattyBalaam** [comment]
I agree, but I do see the value in the improved options for some cases. It might be good for someone to create a spin-off from this repo offering more fully featured variations for when utilities like this might be needed.

**Comment by GiorgiStoynev** [comment]
@ndugger, I don't see extending existing api calls with the ability to remove repetitions in client code is over-complication, as long as no additional logical branches are introduced in function body (e.g. browser flavor handling or anything else that is not already in the DOM/native APIs)
