### ISSUE TITLE
IE version slider postion

### ISSUE THREAD

**Issue by zsalzbank** [HubSpot/youmightnotneedjquery#15]
Fix the IE version slider position to the top of the page when it hits the top.  This will let users switch between versions when actually looking at the code so they can see the differences without having to scroll back and forth  and remember what the previous code looked like.

**Comment by zackbloom** [comment]
Thanks for your feedback.  We'll consider this as we think about the site's design, but I'm going to close it as its more of a stylistic choice than an issue.
