### ISSUE TITLE
`$(el).html(string);` is not exactly equivalent to `el.innerHTML = string;`

### ISSUE THREAD

**Issue by clupasq** [HubSpot/youmightnotneedjquery#151]
The difference between `$(el).html(string);` and `el.innerHTML = string;` is that in cases where the string contains script tags, the jQuery version will not only add those to the DOM, but also execute them. The vanilla JS version will not execute those scripts. 

This is true both for inline as well as external (`src=...`) scripts.

To illustrate, here are two fiddles:
- jQuery executes a script when `.html(string)` is called: https://jsfiddle.net/1z27mawx/
- the inline script is not executed when doing `innerHTML = string`: https://jsfiddle.net/o05ghvt0/1/

In search for a closer alternative to jQuery here is what I made: https://jsfiddle.net/oogspgrp/2/
Please let me know if you see something wrong with this.

**Comment by nickserv** [comment]
I feel like since this is a potential security vector, it's better to continue recommending `el.innerHTML = string;` by default. Perhaps this could be added as a separate example or alternative, though I don't think it would be used as often.

**Comment by Abbondanzo** [comment]
As Nick has mentioned, blindly evaluating scripts is generally discouraged to avoid cross-site scripting. In this case, I'd ere on the side of caution and simply encourage users to reach for `eval` if they intend to execute any strings they receive
