### ISSUE TITLE
.parents()?

### ISSUE THREAD

**Issue by robertvanderelst** [HubSpot/youmightnotneedjquery#153]
Hi,

First of all: Amazing job on the site and the solutions shown! :+1: 

I'm wondering if you could give a proper solution equivalent for the .parents() method in jQuery?

Thanks in advance!

**Comment by radiocity** [comment]
Use the parentNode parameter, Luke
http://www.w3schools.com/jsref/prop_node_parentnode.asp

**Comment by robertvanderelst** [comment]
parentNode gives just the direct parent, not all parents of an element, let alone the ability to travel up the DOM to a certain parent... :)

**Comment by radiocity** [comment]
If you gonna explore [jQuery source code](https://github.com/jquery/jquery/blob/a268f5225cad9ab380494e61a10105cc9eb107e7/src/traversing/var/dir.js), you'll find that the loop used to find all parents.
This is wierd code. I suggest you to use parentNode and check if parent exists

**Comment by nicolo-ribaudo** [comment]
You can use this function, which works on IE9+

``` js
function parents(el, selector) {
    var parents = [];
    while ((el = el.parentNode) && el !== document) {
        if (!selector || matches(el, selector)) parents.unshift(el);
    }
    return parents;
}

parents(element);
parents(element, ".my-class");
```

(The `match` function is defined here: http://youmightnotneedjquery.com/#matches_selector)

**Comment by robertvanderelst** [comment]
Thank you Nicolo! Will give that a go! :) :+1:

**Comment by TheoryOfNekomata** [comment]
I wonder why this is not already included?

**Comment by radiocity** [comment]
Nobody does pull request

**Comment by robsonsobral** [comment]
Today we have [`el.closest('.css-selector')`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest), meaning the closest ancestor which matches the supplied condition.

MDN documents a [polyfill](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill)

```js
if (!Element.prototype.matches)
    Element.prototype.matches = Element.prototype.msMatchesSelector || 
                                Element.prototype.webkitMatchesSelector;

if (!Element.prototype.closest)
    Element.prototype.closest = function(s) {
        var el = this;
        if (!document.documentElement.contains(el)) return null;
        do {
            if (el.matches(s)) return el;
            el = el.parentElement;
        } while (el !== null); 
        return null;
    };
```
