### ISSUE TITLE
Not enough jquery

### ISSUE THREAD

**Issue by ilovejimbo4646** [HubSpot/youmightnotneedjquery#156]

**Comment by nicolo-ribaudo** [comment]
Can you provide some more information?
Which functions would you like to know how to write in vanilla js?

**Comment by ilovejimbo4646** [comment]
All the functions are fine, it's just that the library doesn't include enough jquery.

**Comment by mrfzd** [comment]
@ilovejimbo4646 This is totally confusing!!! What do you mean there isn't enough of jQuery!!! Of course not many functions/methods would be there as part of JavaScript by DEFAULT... otherwise why would there even be a library called jQuery!!!

**Comment by TheFishIsDead** [comment]
you can never have enough jquery. shut up @stylishweb you don't know anything. jquery is love, jquery is life. https://www.needsmorejquery.com

**Comment by mrfzd** [comment]
@TheFishIsDead I didn't actually dissed jQuery!!! It seems you didn't understood me properly... read what I said again!!!
I'm saying of course JavaScript won't have those functions/methods that jQuery currently offers!!! You must write lots and lots of codes to achieve the same result as what jQuery offers out of the box...

Any JavaScript/front end developer MUST know how to code in vanilla JS and not relying on a particular library as sometimes performance of an app is much important than writing an app quickly... jQuery is very poor/bad for using mid to large scale apps...

Peace :+1:

**Comment by yeshomoyeshomoyeshomo** [comment]
-1 @stylishweb not enough jquery in your reply. You should've used jquery's built in "reply" function.

**Comment by MattyBalaam** [comment]
I think the main issue is that FishIsDead should have explicitly used the native string.sarcasm()

**Comment by mrfzd** [comment]
@ilovejimbo4646 @TheFishIsDead @ilovejimbo4646 You guys need to seriously grow up... that's my first and most important advice to you guys... then once that's sorted then start worrying about non-human language as it's clear to everyone that you guys hardly understand English properly!!!

Sort yourselves out guys, never seen anybody like you guys, acting like 2 year olds!!! You +1 your own comments!!! Seriously...!!!
