### ISSUE TITLE
‘extend()’.  How about this?

### ISSUE THREAD

**Issue by csywweb** [HubSpot/youmightnotneedjquery#161]
`extend: function(obj){`
 `var newobj = JSON.parse(JSON.stringify(config));`
`for(var i in obj){`
 `newobj[i] = obj[i];`
`}`
 `return newobj;`
 `},`

**Comment by victornpb** [comment]
This is not the way to clone an object.

What if you want to extend this `{a: 1, b: /foo/, c: function(){}}`?
