### ISSUE TITLE
document.querySelectorAll() problems

### ISSUE THREAD

**Issue by ghost** [HubSpot/youmightnotneedjquery#163]
When I did `document.querySelectorAll('element').style.backgroundColor = 'black';`, But chrome says style is undefined...

**Comment by zackbloom** [comment]
That generally means `element` is not a selector which matches an element
on the page.

**Comment by ghost** [comment]
Hmm. Let me test

**Comment by ghost** [comment]
Press F12 on here, go to console and type in `var elem = document.querySelectorAll("#js-repo-pjax-container")`, press enter, and type `elem.` and alot of stuff except `document.querySelector` stuff pops up.

**Comment by dierkerd** [comment]
a call to [document.querySelectorAll](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll)('element') will always return an array like object... Either an empty array if the query doesn't match anything or a [NodeList (array like) object](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) if it matches one or more items. In all modern browsers you can call the[ .forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/forEach) method to access each element returned.

To do what you're trying to do you'd use something like: 

``` javascript
document.querySelectorAll('element').forEach(function(e) {e.style.backgroundColor='black'})
```

**Comment by zackbloom** [comment]
Ah yea, I didn't notice it was `querySelectorAll`.  You mean to be using
`querySelector`.

**Comment by ghost** [comment]
Exactly what I thought. Should I open a pull request to fix this, or will you do it?

**Comment by zackbloom** [comment]
Sorry, does that line appear in the docs somewhere? Is that the issue?

**Comment by ghost** [comment]
Yes

**Comment by MattyBalaam** [comment]
Might be helpful if you let people know exactly where.

**Comment by ghost** [comment]
Ok, issue is solved. Do

``` javascript
var s = document.querySelectorAll("#my .awesome selector");
for (var i = 0; i < s.length; i++) {
    var elem = s[i]
    // use YMNNJ code here, but do it on elem
}
```

**Comment by ghost** [comment]
Or `document.querySelectorAll('element').forEach(function(e) {e.style.backgroundColor='black'})`

**Comment by MattyBalaam** [comment]
Depending on the browser that may not work, for better compatibility it is generally suggested to use:

```
var els = document.querySelectorAll('element');
Array.prototype.forEach.call(els, function( el ){
...
}
```

**Comment by ghost** [comment]
ah, .call, how I love you. And thanks
