### ISSUE TITLE
Improve `ready` example

### ISSUE THREAD

**Issue by adamschwartz** [HubSpot/youmightnotneedjquery#165]
Suggestion from Twitter:
https://twitter.com/analog_nico/status/774404724963487744

**Comment by eng1neer** [comment]
+1 It gives incorrect timing at least on IE10 when readyState == 'interactive'. DOM might not be ready yet. Why not test `document.readyState == 'complete'` instead of `document.readyState != 'loading'`

**Comment by jq-87** [comment]
does this solve it? https://github.com/HubSpot/youmightnotneedjquery/commit/3907dbb7b254620479b9477886c5c6b021845cb2
