### ISSUE TITLE
Tiny Components

### ISSUE THREAD

**Issue by Wizek** [HubSpot/youmightnotneedjquery#17]
I am a big fan of tiny components, therefore I think big monolithic libraries, like jQuery should be phased out. It should be very easy to load only the pieces you actually need. This would be especially important for libraries.

Thank you for popularizing this point of view.

However, people shouldn't implement everything for themselves either: people should be able to (re)use code that has already been written -- and written well.

Do you think it would be a good idea to make some (of the more complex ones, if not all) of your proposed alternatives available with [loadr](https://github.com/Wizek/loadr)?
An example:

They could be available like

```
require github://HubSpot/ajax/json
```

which would load

``` js
window.ajax = window.ajax || {}
ajax.json = function (url, cb) {
  request = new XMLHttpRequest
  request.open('GET', url, true)
  request.send()

  request.onload = function() {
    cb(JSON.parse(request.responseText))
  }
}
```

that could be used like

``` js
ajax.json('/path/to.json', handlerFn)
```

Because
1. Everyone loves abstraction and memorable APIs.
2. Programmers would still place these snippets into function bodies. Code feels cold naked. Let's do it for them, shall we?

What do you think?

P.S. Nice to see new educational JavaScript material popping up using ASI. :) Thanks for that, too.

**Comment by zackbloom** [comment]
I'm all for small packages, but I'm not so sure we should be endorsing a specific project like loadr.  I could however see the site linking to projects which provide more targeted implementations of various bits.  I'll make a wikipage to keep track of them for now.

**Comment by zackbloom** [comment]
https://github.com/HubSpot/youmightnotneedjquery/wiki/Alternatives

**Comment by Wizek** [comment]
No need to endorse right away. Check it out and decide afterwards. :)
