### ISSUE TITLE
Offline Accessibility

### ISSUE THREAD

**Issue by yomete** [HubSpot/youmightnotneedjquery#173]
This is a great site/thing/product and I use it almost every time as a reference.
Good one!

Have you ever thought about making a PWA and using service workers to cache the content so the whole site is easily accessible in areas with a 2G connection or even offline accessibility.

I'd be happy to help.
Cheers

**Comment by ghost** [comment]
Just download it as PDF/HTML. It would work , i think (some browsers can).

**Comment by ghost** [comment]
I downloaded it in chromium (Ctrl+S) and anything works w/o connection.

**Comment by yomete** [comment]
Yes, that would work but one could argue that doesn't extend the whole power of offline accessiblity.
What about mobile users? Can they save webpages on their devices?

**Comment by thecotne** [comment]
Chrome on android has Download button. So yes they can.

**Comment by yomete** [comment]
Alright. Looks like this has solved itself.
Thanks for the feedback.
