### ISSUE TITLE
Add "IE Version" toggle to query string

### ISSUE THREAD

**Issue by styfle** [HubSpot/youmightnotneedjquery#180]
I think changing the IE Version should change the query string so we can bookmark it.

![image](https://user-images.githubusercontent.com/229881/29028038-06bf6d9e-7b51-11e7-96ae-615ef66b8d85.png)

Also, it would be nice to add IE 11 (if there are any differences)

**Comment by FranklinYu** [comment]
+1 to IE 11. It would be even better if I can choose Edge.
