### ISSUE TITLE
Add removeAttribute for removing attributes

### ISSUE THREAD

**Issue by Flimm** [HubSpot/youmightnotneedjquery#183]
We have code for how to get an element's attributes: http://youmightnotneedjquery.com/#get_attributes

We also have code for how to set an element's attributes: http://youmightnotneedjquery.com/#set_attributes

However, there is no example for how to remove an attribute. This is how you do it with JQuery:

```js
$(el).removeAttr("hidden");
```

Here is how you do it without JQuery, using [`removeAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute):

```js
el.removeAttribute("hidden");
```

I haven't tested this code in IE8, so it would be worth checking that.

**Comment by Abbondanzo** [comment]
It has been added: https://youmightnotneedjquery.com/#remove_attributes
