### ISSUE TITLE
Bug in parseHTML (not working in IE11)

### ISSUE THREAD

**Issue by simonwidjaja** [HubSpot/youmightnotneedjquery#184]
Thanks for the great resource. Using it a lot. But I found an error:

```
// jQuery 
$.parseHTML(htmlString);

//IE9+
var parseHTML = function(str) {
  var tmp = document.implementation.createHTMLDocument();
  tmp.body.innerHTML = str;
  return tmp.body.children;
};
parseHTML(htmlString);
```

The call of document.implementation.createHTMLDocument(); throws an error in good ol' IE11. ("Argument not optional")

**Comment by simonwidjaja** [comment]
Taken from developer.mozilla.org:

**Syntax**
newDoc = document.implementation.createHTMLDocument(title);

**Parameters**
title  Optional (except in IE) .   <!----------------
Is a DOMString containing the title to give the new HTML document.

**Comment by robsonsobral** [comment]
I would suggest you to do a pull request, but... There's already 43 waiting!

**Comment by robsonsobral** [comment]
[Related](https://github.com/HubSpot/youmightnotneedjquery/issues/93)

**Comment by Lcfvs** [comment]
My custom solution, to be able to load an entire web page : https://github.com/nefe/You-Dont-Need-jQuery#3.14 ;)
