### ISSUE TITLE
what's `+new Date()` means ?

### ISSUE THREAD

**Issue by xyzdata** [HubSpot/youmightnotneedjquery#190]
# Q:

> what's `+new Date()` means ?

http://youmightnotneedjquery.com/

![](https://user-images.githubusercontent.com/29531779/38540551-e7a5f1d6-3cce-11e8-878e-3fa9d9fde0e5.png)

I just can't understand it.

# A:

> 一元加操作符以一个加号（+）表示，放在数值的前面，对数值不会产生任何影响。
在对`非数值`应用`一元加`操作符时，该操作符会像 `Number()` 转型函数一样对这个值执行转换。

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number

![image](https://user-images.githubusercontent.com/29531779/38555802-1fbd2834-3cfa-11e8-9b8e-5eb0c7b8a102.png)

![image](https://user-images.githubusercontent.com/29531779/38555814-27849192-3cfa-11e8-8d7b-00696fa82470.png)

![image](https://user-images.githubusercontent.com/29531779/38555820-2b6c7176-3cfa-11e8-8c32-9686f298bb07.png)

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/38542078-7ccb7bce-3cd3-11e8-8fd8-11c7b33683fb.png)

**Comment by victornpb** [comment]
the `+` operator is expecting a number but when it encounters an object it tries to get the numeric value of it by calling `Object.valueOf()` and using it

```js
const x = {}
+x //NaN

const y = { valueOf(){ return 7 } }
+y //7
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf
