### ISSUE TITLE
🔒Enforce https

### ISSUE THREAD

**Issue by mattcdowning** [HubSpot/youmightnotneedjquery#197]
Kind of ironic that a site by two _Cloudflare_ employees wouldn't be served over SSL! Anyhoo, can someone please enforce https for this most excellent site? Instructions [here](https://help.github.com/articles/securing-your-github-pages-site-with-https/).

**Comment by poldixd** [comment]
+1

**Comment by xnekv03** [comment]
please enforce HTTPS
