### ISSUE TITLE
Equivalent of jQuery val()

### ISSUE THREAD

**Issue by stof** [HubSpot/youmightnotneedjquery#199]
While the replacement is quite easy for type of fields (`input`, `textarea` and non-multiple select), it is more tricky for `<select multiple>`. Showing the equivalent would be great

**Comment by bfiessinger** [comment]
this is pretty simple. Instead of writing `$('.element').val()` you can use `node.value`

**Comment by stof** [comment]
please read my description. `node.value` is the answer for simple cases, but it does not work for all types of form elements. Showing only partial equivalents would not be fair.

**Comment by andyps** [comment]
This works for both multiple and non-multiple selects

`Array.from(document.querySelector('#select').options).filter(o => o.selected).map(o => o.value)`
or
`[...document.querySelector('#select').options].filter(o => o.selected).map(o => o.value)`
or
`[...document.querySelector('#select').selectedOptions].map(o => o.value)`
