### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by FranDias** [HubSpot/youmightnotneedjquery#200]
Hey everyone,

Thank you all for your contributions and issue requests. The build is and as far as I can tell has been broken for some time. I took a quick look at fixing the build and can't really tell when over the last 3 years it broke. For me to fix the issue it'd be quicker to build a new site on a modern stack which I'm 🤷‍♂️ on. The site did pick up 1,000 stars over the past year so it seems to still be useful to some people. 

I'd also like to add more value to the site rather than just remaking. Any thoughts on this, for better or worse?

**Comment by FranDias** [comment]
Just went though and called bankruptcy  on a bunch of open PRs. 

Why not give some github credit to people who put time in even though it's not going to be published.

![](https://media3.giphy.com/media/y8Mz1yj13s3kI/giphy.gif?cid=6104955e5d3740c2654433355138ade1&rid=giphy.gif)

**Comment by Richienb** [comment]
@FranDias I'd say we should add code for modern browsers to go with IE8, 9 and 10 so people using modern build tools that transpile the code anyway can have the simplest experience possible.

Anyways, it's about time for the site to be rebuilt. I'd be happy to start working on it for the next few weeks or so. Please add me as a collaborator.

**Comment by sa7mon** [comment]
@FranDias Just came back to the site today. It's a great reference and I really think it would be good to do whatever you have to to get the build working again and deploy all of these changes. Thanks for the handy reference!

**Comment by Richienb** [comment]
// @adamschwartz @FranDias

**Comment by Abbondanzo** [comment]
Builds are working again, reorganized the repository a bit more to (hopefully) make it more obvious where contributions should go. Always open to rebuilding some of the older features and will happily review PRs that anyone makes
