### ISSUE TITLE
page doesn't work

### ISSUE THREAD

**Issue by kampiamodikuesto** [HubSpot/youmightnotneedjquery#201]
from console i can see this 404 load resource erro:

`Failed to load resource: the server responded with a status of 404 ()
spin:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spin:1 Failed to load resource: the server responded with a status of 404 (Not Found)
YouMightNotNeedjQuery:1 Failed to load resource: the server responded with a status of 404 (Not Found)
YouMightNotNeedjQuery:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spin:1 Failed to load resource: the server responded with a status of 404 (Not Found)
YouMightNotNeedjQuery:1 Failed to load resource: the server responded with a status of 404 (Not Found)
count.json:1 Failed to load resource: net::ERR_CONNECTION_REFUSED`

**Comment by FranDias** [comment]
Just looked at http://youmightnotneedjquery.com/ So "page doesn't work" isn't accurate.

Just pasting a console error isn't helpful. Feel free to post a new issue with context of what you were trying to do and how you can't. Also keep in mind https://github.com/HubSpot/youmightnotneedjquery/issues/200

**Comment by kampiamodikuesto** [comment]
i load the page with console log opened and this is the result: https://snag.gy/4AjOLB.jpg 
it's impossible to select "What's the oldest version of IE you need to support?" checkbox 

i'm on osx 10.13.3 + ( chrome | firefox | safari )
