### ISSUE TITLE
Include for...in and for...of in the tool

### ISSUE THREAD

**Issue by ShivamS136** [HubSpot/youmightnotneedjquery#212]
As now javascript supports [for...in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) and [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) to enumerate and iterate respectively. They can replace [$.each on Object](https://api.jquery.com/jQuery.each/#jQuery-each-object-callback) and [$.each on Array](https://api.jquery.com/jQuery.each/#jQuery-each-array-callback).
So the above can be added in the tool.

**eg.**
```javascript
$.each(obj, function(key, value){
...
});
```
can be replaced by
```javascript
for(var key in obj){
var value = obj[key];
...
}
```

**Comment by Abbondanzo** [comment]
Fixed by #282
