### ISSUE TITLE
outerWidth & outerWidth margin calculation

### ISSUE THREAD

**Issue by mdtanrikulu** [HubSpot/youmightnotneedjquery#213]
Hey there!

I would like to ask you a question; 

Isn't it better to have `parseInt(parseFloat(marginLeft/Top) + parseFloat(marginRight/Bottom))` instead of `parseInt(float) + parseInt(float)`, so margin size can be more precise? 

Asking for `outerWidth` here:  https://github.com/HubSpot/youmightnotneedjquery/blob/dbe77b2e55eac9a92ffb34adcbb3633aca0d6744/comparisons/elements/outer_width_with_margin/ie9.js#L5

https://github.com/HubSpot/youmightnotneedjquery/blob/dbe77b2e55eac9a92ffb34adcbb3633aca0d6744/comparisons/elements/outer_width_with_margin/ie8.js#L5

and `outerHeight` here: 

https://github.com/HubSpot/youmightnotneedjquery/blob/dbe77b2e55eac9a92ffb34adcbb3633aca0d6744/comparisons/elements/outer_height_with_margin/ie8.js#L5

https://github.com/HubSpot/youmightnotneedjquery/blob/dbe77b2e55eac9a92ffb34adcbb3633aca0d6744/comparisons/elements/outer_height_with_margin/ie9.js#L5

**Comment by nickserv** [comment]
These examples are already using `parseFloat` to parse the individual values.

**Comment by Abbondanzo** [comment]
Closed by #282
