### ISSUE TITLE
jQuery deep extend polyfill error

### ISSUE THREAD

**Issue by ab14bhardwaj** [HubSpot/youmightnotneedjquery#215]
### Issue
When using jQuery deep extend polyfill from your [website](http://youmightnotneedjquery.com/) I found out that if we pass a key-value null in one object and deep merge it with another object then in the result the value of key which was sent null initially is coming as an empty object, which should not as per jQuery deep extend function.

### Code
var goku = {
    email: null
}
var vegeta = {
    name: "Saiyan"
}
var deepExtend = function(out) {
  out = out || {};
  for (var i = 1; i < arguments.length; i++) {
    var obj = arguments[i];
    if (!obj)
      continue;
    for (var key in obj) {
      if (obj.hasOwnProperty(key)) {
        if (typeof obj[key] === 'object'){
          if(obj[key] instanceof Array == true)
            out[key] = obj[key].slice(0);
          else
            out[key] = deepExtend(out[key], obj[key]);
        }
        else
          out[key] = obj[key];
      }
    }
  }
  return out;
};
deepExtend({}, goku, vegeta);

### Result
{
  email: {}, 
  name: "Saiyan",
}

 - Email key value should come as null and not as an empty object.
 - When using jQuery deep extend I got results as below:
> $applozic.extend(true, {}, goku, vegeta)
> { email: null, name: "Saiyan",}

**Comment by Abbondanzo** [comment]
This is because `null` succeeds the `typeof obj[key] === 'object'` check, which recursively calls `deepExtend` and returns an empty object. Good catch
