### ISSUE TITLE
Allow targeting modern browsers

### ISSUE THREAD

**Issue by Richienb** [HubSpot/youmightnotneedjquery#228]
It would be useful to provide code that only works in modern browsers. This means people using bundlers can just focus on writing readable code.

For example, `$().remove()` is this in IE10:

```js
element.parentNode.removeChild(element)
```

but is this in modern browsers:

```js
element.remove()
```

A lot can also be said for ajax APIs as well with the introduction of window.fetch

**Comment by stephanvierkant** [comment]
See #222
