### ISSUE TITLE
Add list of open source projects lacking jQuery as a dependancy

### ISSUE THREAD

**Issue by dannydes** [HubSpot/youmightnotneedjquery#25]
It would add further value to the incentive as to know people are using these tips with successful results!

e.g. (sorry for the self advert) github.com/dannydes/Awesome-Gallery

**Comment by zackbloom** [comment]
I imagine that this list is going to get pretty long, but let's go for it: https://github.com/HubSpot/youmightnotneedjquery/wiki/Libraries-Which-Don't-Require-jQuery
