### ISSUE TITLE
Errors when loading in Internet Explorer 11

### ISSUE THREAD

**Issue by nickserv** [HubSpot/youmightnotneedjquery#265]
The app mostly works in Internet Explorer 11, as comparisons load and the version can be changed, but there are errors:

## `fetch` not supported so stargazer count can't load
```
SCRIPT1010: Expected identifier
https://youmightnotneedjquery.com/js/index.js (5,20)
```
## Parse error in HubSpot analytics
```
SCRIPT1006: Expected ')'
https://js.hubspot.com/analytics/1661747700000/51294.js (43,21812)
```

**Comment by jarikmarwede** [comment]
Maybe we can use [Polyfill.io](https://polyfill.io/v3/url-builder/) to add the polyfill for `fetch`. That would allow me to easily add one for `URLSearchParams` in https://github.com/HubSpot/youmightnotneedjquery/pull/248

**Comment by nickserv** [comment]
See https://github.com/HubSpot/youmightnotneedjquery/pull/264#issuecomment-1232272785
