### ISSUE TITLE
Replace slider with radio buttons or select

### ISSUE THREAD

**Issue by nickserv** [HubSpot/youmightnotneedjquery#272]
We're suggesting the ES6 option be moved to a toggle separate from the IE slider (see https://github.com/HubSpot/youmightnotneedjquery/pull/271#issuecomment-1232447117)

**Comment by nickserv** [comment]
I've changed my mind. Radio buttons or select would have better accessibility because they have built in labels and keybinds, and slider should really be used when the exact value isn't important.

**Comment by Richienb** [comment]
> I've changed my mind. Radio buttons or select would have better accessibility because they have built in labels and keybinds, and slider should really be used when the exact value isn't important.

What would the IE slider become then? A set of 3 radio buttons?

**Comment by mscuthbert** [comment]
> > I've changed my mind. Radio buttons or select would have better accessibility because they have built in labels and keybinds, and slider should really be used when the exact value isn't important.
> 
> What would the IE slider become then? A set of 3 radio buttons?

I don't know that there needs to be one.  We can display all the ie8, ie9, ie10, ie11 files and people who need to support a specific version of IE can look and see "oh, that solution is for ie10+ only; I need to support ie8, so I'll look at the next example or just use JQuery".

Poor souls still needing to support IE 8.

**Comment by nickserv** [comment]
I was thinking of something like one of these inputs:

[<img width="420" alt="image" src="https://user-images.githubusercontent.com/927220/188301896-f8ccda59-4f86-495f-9872-d854384935ac.png">](https://sdrbje.csb.app/)


[Source](https://codesandbox.io/s/you-might-not-need-jquery-ui-prototype-sdrbje?file=/index.html)

**Comment by Richienb** [comment]
I read @mscuthbert's solution of displaying all of the older browser files at the same time and realised it actually makes more sense since then people can look at the implementations for these old browsers to determine how old they want to still be supporting.

**Comment by nickserv** [comment]
So you think a single checkbox would be enough?

**Comment by Richienb** [comment]
yes

![A checkbox controls whether exmaples for internet explorer or modern browsers are shown](https://user-images.githubusercontent.com/29491356/188302540-9300959b-3125-4143-a401-b5ab91414ad5.png)

**Comment by nickserv** [comment]
I'm also ok with that, as long as it has an accessible label.

**Comment by Richienb** [comment]
> I'm also ok with that, as long as it has an accessible label.

Yup, I've finished the rewrite now - check it out.
