### ISSUE TITLE
Don't change URL query params by default

### ISSUE THREAD

**Issue by nickserv** [HubSpot/youmightnotneedjquery#276]
I don't think we should immediately change the default URL to `?support=es6`, as things could break if a user comes back to the page and the support string changed (see #272), and it prevents you from getting the latest version if a newer one is released.

**Comment by jarikmarwede** [comment]
Shouldn't be a problem anymore once the default becomes `?support=modern`. But I agree that for style reasons we could leave the query string blank if the default version is selected.
