### ISSUE TITLE
Custom Event in IE8

### ISSUE THREAD

**Issue by ethanius** [HubSpot/youmightnotneedjquery#29]
On the line 1201 you suggest to use jQuery, because IE8 does not know any custom events. That is true, but since you already suggest something else than vanilla JS solution, why not https://github.com/ondras/ie8eventtarget ? That is a polyfill for actually all the standard-based events + it does the trick for a custom event. I know you want to show that it can be done without polyfills, but since this one can't be done without any, I find this one better than actually using jQuery.

**Comment by zackbloom** [comment]
Mind adding it to: https://github.com/HubSpot/youmightnotneedjquery/wiki/Alternatives
