### ISSUE TITLE
Trigger Native needs to be looked into

### ISSUE THREAD

**Issue by ianthedev** [HubSpot/youmightnotneedjquery#323]
The current [proposed vanilla version of trigger native](https://youmightnotneedjquery.com/#trigger_native) is:

```javascript
function trigger(el, eventType) {
  if (typeof eventType === 'string' && typeof el[eventType] === 'function') {
    el[eventType]();
  } else {
    const event =
      eventType === 'string'
        ? new Event(eventType, {bubbles: true})
        : eventType;
    el.dispatchEvent(event);
  }
}

trigger(el, 'focus');
// For a full list of event types: https://developer.mozilla.org/en-US/docs/Web/API/Event
trigger(el, new PointerEvent('pointerover'));
```

I'm not sure I understand the sixth line `eventType === 'string'`

We would not pass `'string'` as the second argument of the function, would we?

Maybe that line is missing `typeof` at the start? But if that's true, that would be a duplicate effect of the `typeof eventType === 'string'` of the `if` statement above.

I would be appreciated if someone could explain.

**Comment by Abbondanzo** [comment]
Good catch--it should have a `typeof` check in front of `eventType`. To answer your question about the duplicate effect I'll provide a counterexample: form elements have a native submit function so we'd do something like `trigger(maybeFormElement, "submit")` but we want to ensure that the function is actually on the element before blindly executing it and potentially raising an exception.

**Comment by ianthedev** [comment]
Thanks for the update. Maybe the 2nd line can be simplified as `if (typeof el[eventType] === 'function') {` because the `typeof eventType === 'string'` does not really help. An error will occur anyway if the second argument is not a string nor an event object.
