### ISSUE TITLE
The `:visible` selector is not listed

### ISSUE THREAD

**Issue by alexander-schranz** [HubSpot/youmightnotneedjquery#334]
Depending on the following answer on stackoverflow: https://stackoverflow.com/questions/19669786/check-if-element-is-visible-in-dom#33456469

it is:

```js
function isVisible(element) {
    return !!( element.offsetWidth || element.offsetHeight || element.getClientRects().length );
}
```

https://github.com/jquery/jquery/blob/bcaeb000b777c018ad5d18e01be5060caa8cb158/src/css/hiddenVisibleSelectors.js#L8-L10

Another modern alternative is the IntersectionObserver: https://stackoverflow.com/questions/19669786/check-if-element-is-visible-in-dom#68961408

```js
const el = document.getElementById("your-target-element");
const observer = new IntersectionObserver((entries) => {
    if(entries[0].isIntersecting){
         // el is visible
    } else {
         // el is not visible
    }
});

observer.observe(el); // Asynchronous call
```

**Comment by Abbondanzo** [comment]
Added these in #337. The `IntersectionObserver` solution is nice but it's async so it might be a bit more confusing for those looking to switch from something synchronous
