### ISSUE TITLE
Example with error

### ISSUE THREAD

**Issue by JoaoCapoAlm** [HubSpot/youmightnotneedjquery#335]
In the [EFFECTS](https://youmightnotneedjquery.com/#effects) has two erros in the example

In "Fade In" > "MODERN"  the correct example is `el.classList.replace('hide', 'show');`

In "Fade Out" > "MODERN" the correct example is `el.classList.replace('show', 'hide');`

**Comment by Abbondanzo** [comment]
Thanks for catching this, it should be fixed now!
