### ISSUE TITLE
Some example, why not jquery for readibility ?

### ISSUE THREAD

**Issue by HuangChiEn** [HubSpot/youmightnotneedjquery#340]
First, thanks for this amazing repo for exploring some native api supported by modern browser, while i'm a newbi in this field.
Some example show that the modern web-api can deal with the same functionality as Jquery did. however, my question is should we let the code more hard to read just because some modern web-api support this function ?

Examples :
![image](https://github.com/HubSpot/youmightnotneedjquery/assets/52521165/6b58b210-f827-4039-a93a-76f1987fc5ee)
encapsulate fade_in, fade_out detail in JQuery seems better then write the css style to control the behavior, at least more shorter without cost.

![image](https://github.com/HubSpot/youmightnotneedjquery/assets/52521165/7a3c17ed-263b-4725-b717-9b508aa701d3)
Query selectForAll and then filter out could be consider as two stage, in contrast, jQuery keep it in very simple string to fullfill it.

![image](https://github.com/HubSpot/youmightnotneedjquery/assets/52521165/6c8bb7a3-bf11-4500-882b-3b444269df72)
Also, web-api reveal some detail i don't want to know while i chked the components is visible or not ~

**Comment by Abbondanzo** [comment]
The goal of replacing or removing jQuery isn't always to make your code more or less readable, it's to remove the bloat of an entire library for the sake of the one or two functions you may need. jQuery is several hundreds of kilobytes that has to ship alongside your library or application. And you can imagine that if every library author included their own version of it, you'd see the size of your consuming library or application balloon even larger.

Let's take a look at the latest version of jQuery that is posted, 3.7.0, and the examples that you have posted here.

|jQuery|Fade|Contains|Hidden/Visible|Total Raw|
|-|-|-|-|-|
|30.88kb (min, gzip)/87462 bytes (min)|221 bytes (raw)|93 bytes (raw)|208 bytes (raw)|522 bytes|

Our pure implementations for these 3 features makes up just 0.6% of the total size of jQuery. That's a massive win for reducing the size of the code we need to send over the wire.

With all of this in mind, if you find your code easier to maintain _with_ jQuery, then you should absolutely use it! This project isn't meant to dig at the versatility of jQuery--it's extremely well designed and powers a massive amount of the Internet. It's perfectly reasonable to reach for a concise, clear code base at the expense of 10s of kilobytes unless you're trying to shave milliseconds off your load times. Should you opt to include it via CDN, chances are that a good number of your users will probably have it cached anyhow. Modern browsers provide a great number of alternatives, but not all of them are as clear and concise.

Instead, this project is meant to give you an alternative. It's important to be a good custodian to your fellow developers and to your users, to strive to provide a library that uses a minimal footprint and is considerate to poor network connections.

**Comment by mariocosmi** [comment]
As jQuery was already a standard many years ago, why people invented 'modern javascript' instead of making jQuery native in the browser?

**Comment by nickserv** [comment]
Many modern web features have been influenced by jQuery, but they can't have exactly the same syntax as that would break websites that already use jQuery.

**Comment by Abbondanzo** [comment]
Going to close this one out, hopefully my comment above contains enough information to answer your original question
