### ISSUE TITLE
Unnecessary return of undefined in modern next and prev

### ISSUE THREAD

**Issue by jhenly** [HubSpot/youmightnotneedjquery#341]
> Related to #331

Just focusing on the modern `next`, but `prev` is almost identical.

Looking at the implementation of `next`:

```javascript
function next(el, selector) {
  if (selector) {
    const next = el.nextElementSibling;
    if (next && next.matches(selector)) {
      return next;
    }
    return undefined;
  } else {
    return el.nextElementSibling;
  }
}
```

We can see the function may return an `Element` object, `undefined` or `null`.  Since the [`Element.nextElementSibling`](https://developer.mozilla.org/en-US/docs/Web/API/Element/nextElementSibling) read-only property may return an `Element` object or `null`, and `undefined` is returned explicitly.

I propose the `next` function be limited to returning either an `Element` object or `null`. The possibility of having `undefined` returned just adds ambiguity.

Also, nothing can be gleaned from having `undefined` returned. If `selector` is given, then `undefined` is returned if `next` is `null` or `next.matches(selector) == false`. You would have to check if `el.nextElementSibling === null` to figure out why `undefined` was returned.

---

I refactored the `next` implementation in the following way:

```javascript
function next(el, selector=null) {
  const next = el.nextElementSibling;
  if (!selector || (next && next.matches(selector))) {
    return next || null;  // Element | null
  }
  return null;
}

// ... or ...

function next(el, selector=null) {
  const next = el.nextElementSibling;
  if (!selector || next?.matches(selector)) {
    return next || null; 
  }
  return null;
}
```

You could also take it a step further and return `null` if `!(el instanceof Element)`, rather than throwing, similar to the behavior of jQuery:

```javascript
console.log($().next());
// n.fn.init [prevObject: n.fn.init, context: undefined]
```

```javascript
/** @param {Element} el  @param {string?} selector */
function next(el, selector=null) {
  if (el instanceof Element) {
    const next = el.nextElementSibling;
    if (!selector || (next && next.matches(selector))) {
      return next; 
    }
  }
  return null;
}
```

**Comment by jhenly** [comment]
After posting I realized another scenario in which `undefined` would be returned: if `el` is an object with no `nextElementSibling` key. In which case, regardless of a `selector` being specified, `undefined` is returned. And in this scenario `null` ends up being the ambiguity.

**Comment by Abbondanzo** [comment]
> I propose the next function be limited to returning either an Element object or null. The possibility of having undefined returned just adds ambiguity [...] nothing can be gleaned from having undefined returned

The function returning a falsy value is unambiguous--no such element exists--but it would be helpful to be consistent on our return types. We already deviate from jQuery's return value of an object where matching siblings do not exist, so we can also deviate from undefined behavior such as passing in a non-element parameter to the function where an element is expected. The vast majority of our examples would have to be updated with `instanceof` checks to guarantee runtime safety. I'll make the correction on the return type

**Comment by Abbondanzo** [comment]
#342 should address this
