### ISSUE TITLE
Example for `scrollTop` not working

### ISSUE THREAD

**Issue by heurteph-ei** [HubSpot/youmightnotneedjquery#343]
Page https://github.com/HubSpot/youmightnotneedjquery/blob/dev/src/comparisons/elements/scroll_top/modern.js is wrong.
## Initial
```
function scrollTop(el, value) {
  if (value === undefined) {
    return el.pageYOffset;
  } else {
    if (el === window || el.nodeType === 9) {
      el.scrollTo(el.pageXOffset, value);
    } else {
      el.pageYOffset = value;
    }
  }
}
```

## Problem
`.pageYOffset` is only available on window, not on Element or body.
The same probably for scrollLeft...

**Comment by Abbondanzo** [comment]
Thanks for calling this out! It should be fixed by #344
