### ISSUE TITLE
Specify append is only for text

### ISSUE THREAD

**Issue by luisAzcuaga** [HubSpot/youmightnotneedjquery#345]
I'd suggest changing or specifying that vanilla js's `element.append(newElement)` only appends **text**, and if HTML whats to be appended to an element, avoid using:
```js
element.innerHMTL =+ newElement
``` 
Since it repaints the innerHTML of `element`
Instead use:
```js
element.insertAdjacentHTML('beforeend', newElement)
```

**Comment by Abbondanzo** [comment]
`element.append(el)` also takes elements in addition to raw text ([see spec here](https://developer.mozilla.org/en-US/docs/Web/API/Element/append)). We don't suggest using `innerHTML` for any of our prepend/append examples
