### ISSUE TITLE
Remove Class RegExp is unreliable

### ISSUE THREAD

**Issue by darrell-newman** [HubSpot/youmightnotneedjquery#35]
I don't think the remove class RegExp implementation works correctly. Currently it's this:

```
el.className = el.className.replace(new RegExp('(^| )' + className.split(' ').join('|') + '( |$)', 'gi'), ' ')
```

For example, if the element has classes 'a b ab' and you try to remove 'a b' it will also strip the 'b' from 'ab'. The joined | needs parentheses.

It also struggles with repeated classes like 'a a a'. Trying to remove 'a' will only remove some of them. I believe this is because replacement spaces can't count towards a match.

I've been experimenting and this is what I've come up with so far:

```
el.className = (' ' + el.className.replace(/ /g, '  ') + ' ')
    .replace(new RegExp(' (' + className.split(/ +/).join('|') + ') ', 'gi'), '')
    .replace(/ +/, ' ');
```

**Comment by zackbloom** [comment]
Good point, how about:

``` javascript
el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ')
```

**Comment by darrell-newman** [comment]
Using \b won't handle hyphens in class names correctly.

You still need to add parentheses around that middle | section or it'll fail for my first test case.

**Comment by zackbloom** [comment]
I can't actually reproduce the first issue (the need for parens), but the hyphenated class issue is a problem.

**Comment by darrell-newman** [comment]
Here's a complete test case for the first issue:

```
function removeCls(el, className) {
    if (el.classList) {
        el.classList.remove(className);
    }
    else {
        el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
    }
}

var span = document.createElement('span');

span.className = 'a b cab';

removeCls(span, 'a b');

alert(span.className);
```

It's a bit more subtle than that though. Is the removeCls function supposed to support space-separated classes as an argument or not? The RegExp version seems to suggest yes (it splits and joins them) but it then gives the wrong result. The classList implementation just throws an error.

**Comment by zackbloom** [comment]
The conclusion we came to when dealing with the same issue on add class, was that we need two comparisons, one called 'add class', the other called 'add classes'.  The jQuery would be the same for both, but the js will differ.
