### ISSUE TITLE
contains

### ISSUE THREAD

**Issue by 7cc** [HubSpot/youmightnotneedjquery#39]
http://youmightnotneedjquery.com/#contains

``` js
$.contains(document.body, document.body) // false
document.body.contains(document.body) // true
```

this can be pollyfilled easily, but it is confusing to use the same name, isn't it?

``` js
function contains(el, child) {
  if (el !== child) {
    return el.contains(child)
  }
    return false
}
```

``` js
$.contains(document, document) // false
contains(document, document) // false
document.contains(document) // true
```

Rename?

**Comment by zackbloom** [comment]
What would we rename it? `partOf`?  I ended up just incorporating your change.

**Comment by 7cc** [comment]
First of all, the code needs to be changed to do the same thing with jQuery. IE doesn't implement `Node.contains` (= document.contains).
In that case, my recommendation is `$contains`. Using the first letter $ makes it easy to understand the method is a jQuery alternative.

As long as comparing elements, no modification is required. let's name it `partOf`, and add a note.
