### ISSUE TITLE
Ehem. Only IE? Ehem.

### ISSUE THREAD

**Issue by dscho** [HubSpot/youmightnotneedjquery#4]
So you have this beautiful website with tons of useful information and then the only web browsers that are ever mentioned are only those that have actually fallen out of favor in many parts of this planet.

Maybe there should be at least a note that Firefox and Chrome have none of those IE problems?

**Comment by amitburst** [comment]
My guess is that the author assumed (somewhat fairly) that web developers reading the website know that other modern browsers support most if not all of these snippets, but we have to make some compromises depending on what versions of IE we want to support.

**Comment by levick** [comment]
Agree with @amitburst. I think it is clear.

**Comment by zackbloom** [comment]
Everything listed under IE10 is supported by, at worst, FF 11 I believe.  In other words, everything you see for all versions of IE is fully supported by the evergreen browsers.

**Comment by jefflembeck** [comment]
Any chance you'll add Android to this as well? With Android 2.3 hovering around 20% of the Android marketshare and Android making up as much as 80% of the total smartphone marketshare, that's a lot of people with that browser.

**Comment by wookiehangover** [comment]
> IE10 is supported by, at worst, FF 11 I believe

Evidence is better than beliefs. This is JavaScript creationism. https://gist.github.com/rwaldron/8720084#file-reasons-md

**Comment by zackbloom** [comment]
It's a pet peeve of mine that the jQuery comments tend to say 'IE' not qualified with a version, making comparisons like that difficult.  If you can bring up specific incompatibilities, I'll be happy to address them as well as I can.

**Comment by tomByrer** [comment]
> Android 2.3 hovering around 20% of the Android marketshare

Good point.  Is there a test suite that those with a v2.3 device can quickly check out?  CanIUse is sometimes helpful, sometimes not.
