### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by 7cc** [HubSpot/youmightnotneedjquery#43]
http://youmightnotneedjquery.com/#empty
## table

> innerHTML properties of the table and tr objects are read-only

http://msdn.microsoft.com/en-us/library/ms532998%28v=vs.85%29.aspx#TOM_Create

IE8
## select

Removing all children of `select` causes incorrect display bug.

take a look at jQuery source empty().
`elem.options.length = 0`
http://bugs.jquery.com/ticket/12336

IE8, 9

**Comment by zackbloom** [comment]
Moved onto the wiki: https://github.com/HubSpot/youmightnotneedjquery/wiki/Issues-Empty

Thanks @7cc
