### ISSUE TITLE
FadeIn didn't work

### ISSUE THREAD

**Issue by individual11** [HubSpot/youmightnotneedjquery#44]
I ran it in a bookmarklet, and it wasn't increasing the opacity at all (Chome 31). It seemed like it might have been concatenating the value as if it were a string for some reason.

I change the line to this

```
el.style.opacity = Number(el.style.opacity) + (new Date - last) / 400;
```

and it seemed to fix it right up.

**Comment by zackbloom** [comment]
We've modified fade in recently, I don't think this is still an issue.

**Comment by 7cc** [comment]
@individual11 is right.

**Comment by zackbloom** [comment]
Should be fixed, thanks guys.
