### ISSUE TITLE
Create elements

### ISSUE THREAD

**Issue by medicalwei** [HubSpot/youmightnotneedjquery#48]
The way creating elements using jQuery syntax below should be documented.

``` JavaScript
var el = $("<div/>").text("Hello");
```

JavaScript native:

``` JavaScript
var el = document.createElement("div");
var text = document.createTextNode("Hello");
el.appendChild(text);
```

Ref: https://developer.mozilla.org/en-US/docs/Web/API/document.createElement

**Comment by Abbondanzo** [comment]
See #226
