### ISSUE TITLE
Is there a way to achieve event delegation without jQuery?

### ISSUE THREAD

**Issue by jokeyrhyme** [HubSpot/youmightnotneedjquery#55]
http://api.jquery.com/on/

It seems like W3C DOM Events are still insufficient for this use case.

Is it worth having a "devils advocate" part of the site that shows why jQuery is still handy?

**Comment by wyuenho** [comment]
https://github.com/jashkenas/backbone/pull/2959/files#diff-0d56d0d310de7ff18b3cef9c2f8f75dcL1068

**Comment by matthew-andrews** [comment]
We built this:- https://github.com/ftlabs/ftdomdelegate

Associated write up: [DOM Event Delegation without jQuery](https://mattandre.ws/2014/08/small-beautiful-dom-delegation/)

**Comment by Abbondanzo** [comment]
Closed in favor of #240
