### ISSUE TITLE
Grossly misleading

### ISSUE THREAD

**Issue by rwaldron** [HubSpot/youmightnotneedjquery#6]
You should probably read this: http://en.wikipedia.org/wiki/Compatibility_mode and update your entire site accordingly.

**Comment by zackbloom** [comment]
If you are developing a modern application, I highly suggest you include the tag to keep IE8 out of compatibility mode.

**Comment by wookiehangover** [comment]
@zackbloom just FYI then specifying that in a clear and concise way up front would probably be a good idea. Flippantly closing issues confirms your bias against doing more good than harm.

**Comment by zackbloom** [comment]
There always is a tradeoff between simplicity and completeness, I apologize for any confusion.
