### ISSUE TITLE
Shim for class manipulation

### ISSUE THREAD

**Issue by dannydes** [HubSpot/youmightnotneedjquery#64]
Suggest the following shim for IE9 and below: https://developer.mozilla.org/en-US/docs/Web/API/Element.classList#wrapper

Thanks again for the awesome reference.

**Comment by Abbondanzo** [comment]
Since we're only trying to provide vanilla JS implementations to jQuery functions, this wouldn't fit as a comparison. However, if there's a good polyfill resource, we'd be happy to add it to the alternatives list
