### ISSUE TITLE
Potential issue with extend

### ISSUE THREAD

**Issue by adamschwartz** [HubSpot/youmightnotneedjquery#66]
[Tweet from Rod_Yan](https://twitter.com/Rod_Yan/status/457985003775729664)

**Comment by m2w** [comment]
I can corroborate this. Nested objects will not be copied unless:

``` js
if (typeof obj[key] === 'object')
  out[key] = deepExtend(out[key], obj[key]);
```

**Comment by phelma** [comment]
PR #148 includes the fix from the tweet
