### ISSUE TITLE
CustomEvents in IE9 don't work as written

### ISSUE THREAD

**Issue by j-ro** [HubSpot/youmightnotneedjquery#67]
I believe it should be this instead:

``` javascript
if (typeof CustomEvent === 'function') {
  var event = new CustomEvent('my-event', {detail: {some: 'data'}});
} else {
  var event = document.createEvent('CustomEvent');
  event.initCustomEvent('my-event', true, true, {some: 'data'});
}

el.dispatchEvent(event);
```

In the current version, the if statement passes (because window.CustomEvent is an object) but the new statement after that fails (because IE9 doesn't really support custom events).

**Comment by j-ro** [comment]
(updated to make it IE9, not 8....)

**Comment by heychris** [comment]
Second this...

**Comment by thomaslecoeur** [comment]
+1

**Comment by jayenashar** [comment]
https://github.com/HubSpot/youmightnotneedjquery/pull/152

**Comment by myfonj** [comment]
<ins>NM, was telling BS. IE11 goes the standard `document.createEvent` path. And the docs probably speak about event instance, thought not explicitly.</ins>

https://msdn.microsoft.com/en-us/library/ff974338%28v=vs.85%29.aspx

<del>

Actually, from MSDN docs [1], `CustomEvent` is *not* even a (constructor) *function* in IE9, but **object** with `.initCustomEvent` ("factory") method.

Smething like this worked for me in IE11 (not tested in IE9):

```JavaScript
function fireCustomEvent(el, name, data) {
	// ... arguments checks
	var event;
	if (CustomEvent && CustomEvent.initCustomEvent) {
		event = CustomEvent.initCustomEvent(name, true, true, { detail: data });
	} else if (document.createEvent) {
		event = document.createEvent('CustomEvent');
		event.initCustomEvent(name, true, true, data);
	} else {
		// bad luck
	}
	if (el.dispatchEvent) {
		el.dispatchEvent(event);
	} else {
		// ?
	}
}
```
</del>
