### ISSUE TITLE
element.find() is not quite equivalent to element.querySelectorAll()

### ISSUE THREAD

**Issue by agamemnus** [HubSpot/youmightnotneedjquery#70]
element.querySelectorAll can work well in most cases, but they are not equivalent in some cases.

```
// 2: Gets all divs except parent.
console.log ($(document.body).find('* > div').length)

// 3: Gets all divs including parent.
console.log ((document.body).querySelectorAll('* > div').length)

// Gets only elements matching from source/parent element, without recursion. No equivalent in pure JS.
console.log ($(document.body).find('> div').get(0).innerHTML)
```

http://jsfiddle.net/bezd8/

**Comment by zackbloom** [comment]
I may not be understanding what you're referring to, but you can call `querySelectorAll` on any DOM node to get matches inside it:

``` javascript
someElement.querySelectorAll('.cats');
```

**Comment by agamemnus** [comment]
I know! Check out the jsfiddle...

Edit: my bad.. forgot to include jquery link in the fiddle.

**Comment by timmfin** [comment]
For anyone else that stumbles into this, here is [a decent summary](http://stackoverflow.com/questions/11503534/jquery-vs-document-queryselectorall) (visit some of the links/fiddles too) of the pros/cons of `jquery` vs `querySelectorAll`.

The biggest issue that sticks out to me (assuming it hasn't been elsewhere addressed in the past 5+ years) is how `someElement.querySelectorAll('.element-outside-someElement .cats');` [returns different results](http://jsfiddle.net/QdMc5/) than `jQuery(someElement).find('.element-outside-someElement .cats');`

**Comment by varemenos** [comment]
`DOMElement.querySelectorAll` doesn't behave like `$Element.find`.

Here are some links discussing the issue:

http://ejohn.org/blog/thoughts-on-queryselectorall/
https://www.lvh.io/posts/queryselectorall-from-an-element-probably-doesnt-do-what-you-think-it-does.html

**Comment by The4thLaw** [comment]
You need to use `:scope`, as described on this Mozdev article: https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll

No support for IE, though.
