### ISSUE TITLE
insertAdjacentHTML 

### ISSUE THREAD

**Issue by yukulele** [HubSpot/youmightnotneedjquery#76]
`.after()` and `.before()` jQuery methods allow DOM element.

`insertAdjacentHTML` only allow string. It not a reliable replacement for `.after()` and `.before()`.
- MDN
  - https://developer.mozilla.org/en-US/docs/Web/API/Element.insertAdjacentHTML
- jQuery API
  - http://api.jquery.com/after/
  - http://api.jquery.com/before/
- YouMightNotNeedjQuery
  - https://github.com/HubSpot/youmightnotneedjquery/blob/gh-pages/comparisons/elements/after/ie8.js
  - https://github.com/HubSpot/youmightnotneedjquery/blob/gh-pages/comparisons/elements/before/ie8.js

**Comment by yukulele** [comment]
https://github.com/HubSpot/youmightnotneedjquery/pull/77

**Comment by Abbondanzo** [comment]
Fixed by #178
