### ISSUE TITLE
Make user variables distinct from native properties. 

### ISSUE THREAD

**Issue by ghost** [HubSpot/youmightnotneedjquery#81]
Example: 

http://youmightnotneedjquery.com/#add_class

Current State: 

```
if (el.classList)
  el.classList.add(className);
else
  el.className += ' ' + className;
```

Suggested Improvement: 

```
if (el.classList)
  el.classList.add(cName);
else
  el.className += ' ' + cName;
```

Source: http://devdocs.io/dom/element.classname

Other examples might exist (no time to search presently).

**Comment by denniskovshov** [comment]
In my opinion `cName` makes it only worse as encourages reader to use confusing parameter names. `classArg` would be ok. I don't see much benefit anyway.

**Comment by ghost** [comment]
The benefit would be to prevent readers from thinking that the `className` to the left of the `+=` operator represents the same entity as the `className` to the right of `+=`. Different entities shouldn't be given the same name. The way this code example is written won't run. 

The choice of `cName` comes from Mozilla Developer Network. I'm impartial to it specifically.

**Comment by denniskovshov** [comment]
@janaspage  I understand the benefit. Actually, I'm using the code as such and it runs for me. I still think that `cName` is not an ideal name.

**Comment by ghost** [comment]
Sorry, I should be more specific. The code as written works only if the user replaces the last appearance of `className` with the string `'className'`, or if the user previously defines `className` to be a variable whose value is a string naming the desired class. 

My suggestion is not to represent user variables with names that are identical to native property names or reserved keywords, as it potentially complicates debugging. Thanks for your consideration. Cheers.

**Comment by Abbondanzo** [comment]
Going to keep them as-is for now
