### ISSUE TITLE
Hiding should use the [hidden] attribute

### ISSUE THREAD

**Issue by stuartpb** [HubSpot/youmightnotneedjquery#86]
I'm not sure what version of IE they started supporting this in, but it's been around for a while (and I'm pretty sure it's polyfillable).

**Comment by nurbek-ab** [comment]
`hidden` attribute is not meant to be used for this purpose I think. See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-hidden

**Comment by stuartpb** [comment]
`hidden` is meant to be used for things like hidden dialogs, which is mostly how jQuery's "hidden" class is used. (The nominal tabbed-environment case is "meant" to be solved by styling generalized classes, but that's one of those cases that's easier in theory than in practice.)
