### ISSUE TITLE
Incorrect code order on page re: XMLHttpRequest examples

### ISSUE THREAD

**Issue by chiefy** [HubSpot/youmightnotneedjquery#9]
wrong:

```
request = new XMLHttpRequest
request.open('GET', '/my/url', true)
request.send()

request.onload = function() {
  resp = request.responseText

}

request.onerror = function() {

}
```

correct:

```
request = new XMLHttpRequest
request.open('GET', '/my/url', true)
request.onload = function() {
  resp = request.responseText

}

request.onerror = function() {

}
request.send()
```

A co-worker pointed this out.

**Comment by zackbloom** [comment]
I'm actually very curious about this, because my suspicion is that even if the response is 100% cached, the browser won't actually fire the events until the next event loop tick, making the ordering irrelevant.

**Comment by droptable** [comment]
I've observed this behaviour in some Firefox-versions

```
var img = new Image
img.src = 'some_image.png' // immediately calls img.onload if image was cached
img.onload = ... // too late
```

This works:

```
var img = new Image
img.onload = ... 
img.src = 'some_image.png'
```

**Comment by mike-burns** [comment]
If only there was a JS library that provided an abstraction around this that was tried and tested for us.

**Comment by chiefy** [comment]
> send()
> Sends the request. If the request is asynchronous (which is the default), this method returns as soon as the request is sent. If the request is synchronous, this method doesn't return until the response has arrived.
> Note: Any event listeners you wish to set must be set before calling send().

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

**Comment by wilmoore** [comment]
:+1: 

Life is easier if you just put send at the end...always.

**Comment by zackbloom** [comment]
Fixed
