### ISSUE TITLE
IE issue with document.implementation.createHTMLDocument

### ISSUE THREAD

**Issue by adamschwartz** [HubSpot/youmightnotneedjquery#93]
Not really sure, what this means, but seems like he knows what he’s talking about:
https://twitter.com/nathanboktae/status/530418527149514753

@zackbloom

**Comment by arapoport** [comment]
The problem is still present (in Edge) and is a good example why one still might need jquery...

document.implementation.createHTMLDocument() requires an argument in Edge and makes this example invalid:
```
var parseHTML = function(str) {
  var tmp = document.implementation.createHTMLDocument();
  tmp.body.innerHTML = str;
  return tmp.body.children;
};

parseHTML(htmlString);
```

**Comment by sandstrom** [comment]
`createHTMLDocument('')` works
