### ISSUE TITLE
Working with data attributes

### ISSUE THREAD

**Issue by lolmaus** [HubSpot/youmightnotneedjquery#94]
Need a section on subj.

**Comment by bfintal** [comment]
You can just do a `el.getAttribute('data-foo')`

Or as an alternative to `$el.data('foo', 'bar')`, just assign it as a property to the element `el.foo = 'bar'`

**Comment by fabien-michel** [comment]
The correct way is to use the `dataset` attribute on the element. `el.dataset.foo`
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes#javascript_access
